# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 169e917d7f6a960774e7a97ee12a287c0626737ecdf26d71c1945631eccd39dd130a358247b651140fcb45091de825033716ef1de77866f5508fd35c597d97b7

test:
  secret_key_base: 674b3754a7fdf6e4e675fbbfea8efe1832ce53733f7cf1633fd7be989b70d09cc2d1672442a670b108fa26ab376cf2b8f49c39ae9729e90dd0bf6dfc8beec51b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
